name: CI
on:
  pull_request:
    branches: [master]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Clippy
        run: rustup component add clippy
      - name: Format Check
        run: cargo fmt --check
      - name: Build & Lint
        run: cargo clippy --verbose
      - name: Test
        run: cargo test --doc --package derive-visitor
